# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         true
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"
incremental: false
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
gist:
   noscript: false   
#plugins   
gems:
  - jekyll-coffeescript
  - jekyll-paginate

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#站点基础配置
#title: Violet
title: Seven
subTitle: utf7's blog.
description: 这是 utf7 的一个博客,在这里，用来快速记录工作，学习，生活的一点一滴的地方。
url: http://utf7.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: http://utf7.github.io/contact.html

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url: http://utf7.github.io/
  - class: fa-facebook
    url: https://www.facebook.com/seven.chen.756
  - class: fa-github
    url: http://github.com/utf7
  - class: fa-weibo
    url: http://weibo.com/chenyechao
  - class: fa-twitter
    url: http://weibo.com/chenyechao
  - class: fa-rss
    url: http://utf7.github.io/

#作者信息
author:
  link: http://utf7.github.io/
  img: https://avatars2.githubusercontent.com/u/8858683?v=3&s=466

#评论信息
disqus:
  config: true
  id: utf7blog

duoshuo:
  config: false
  id: utf7